-- Pawprint Diaries Database Schema
-- Generated by AI based on source code analysis

-- User and Role Management
CREATE TABLE `user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `username` VARCHAR(255) NOT NULL COMMENT '用户名',
  `password` VARCHAR(255) NOT NULL COMMENT '密码',
  `nick_name` VARCHAR(255) NULL COMMENT '昵称',
  `email` VARCHAR(255) NULL,
  `phone_number` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  `address` VARCHAR(255) NULL,
  `avatar` VARCHAR(255) NULL COMMENT '头像地址',
  `status` INT NULL DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `post_count` INT NULL DEFAULT 0 COMMENT '发帖数',
  `fans_count` INT NULL DEFAULT 0 COMMENT '粉丝数',
  `follow_count` INT NULL DEFAULT 0 COMMENT '关注数',
  `signature` VARCHAR(255) NULL COMMENT '个性签名',
  `is_deleted` INT NULL DEFAULT 0 COMMENT '是否删除：0否 1是',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)
) COMMENT = '用户表';

CREATE TABLE `roles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(255) NOT NULL,
  `role_code` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `status` INT NULL DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) COMMENT = '角色表';

CREATE TABLE `permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `permission_name` VARCHAR(255) NOT NULL,
  `permission_code` VARCHAR(255) NOT NULL,
  `permission_type` VARCHAR(45) NULL COMMENT '权限类型(menu:菜单,button:按钮)',
  `parent_id` BIGINT NULL COMMENT '父权限ID',
  `path` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `status` INT NULL DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) COMMENT = '权限表';

CREATE TABLE `user_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `role_id` BIGINT NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_user_id` INT NULL,
  PRIMARY KEY (`id`)
) COMMENT = '用户角色关联表';

CREATE TABLE `role_permission` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT NOT NULL,
  `permission_id` BIGINT NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) COMMENT = '角色权限关联表';

CREATE TABLE `user_follow` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL COMMENT '关注人ID',
  `followed_user_id` INT NOT NULL COMMENT '被关注人ID',
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) COMMENT = '用户关注表';

-- Cat Management
CREATE TABLE `cat` (
  `cat_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID 主键',
  `catname` VARCHAR(255) NULL COMMENT '猫名',
  `gender` INT NULL COMMENT '性别 1雄性 0雌性',
  `age` INT NULL COMMENT '年龄 单位：月',
  `birthday` DATETIME NULL,
  `avatar` VARCHAR(255) NULL,
  `food` VARCHAR(255) NULL,
  `taboo` VARCHAR(255) NULL,
  `cat_character` VARCHAR(255) NULL,
  `health_status` VARCHAR(255) NULL,
  `sterilization_status` VARCHAR(255) NULL,
  `vaccination_status` VARCHAR(255) NULL,
  `bad_record` VARCHAR(255) NULL,
  `area` VARCHAR(255) NULL,
  `breed` VARCHAR(255) NULL,
  `cat_guide` TEXT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` INT NULL DEFAULT 0,
  `trending` INT NULL DEFAULT 0,
  `like_count` INT NULL DEFAULT 0,
  `is_adopted` INT NULL DEFAULT 0,
  PRIMARY KEY (`cat_id`)
) COMMENT = '猫猫表';

CREATE TABLE `cat_pics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cat_id` BIGINT NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` INT NULL DEFAULT 0,
  `update_user_id` INT NULL,
  `sort_number` INT NULL,
  PRIMARY KEY (`id`)
) COMMENT = '猫咪图片表';

CREATE TABLE `cat_adopt_apply_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cat_id` BIGINT NOT NULL,
  `name` VARCHAR(255) NULL,
  `school_class` VARCHAR(255) NULL,
  `origin` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  `wechat` VARCHAR(255) NULL,
  `apply_user_id` INT NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) COMMENT = '小猫领养申请记录';

CREATE TABLE `cat_time_line_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cat_id` BIGINT NOT NULL,
  `title` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `date` DATE NULL,
  `create_user_id` INT NOT NULL,
  `is_deleted` INT NULL DEFAULT 0 COMMENT '是否删除：1是 0否',
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) COMMENT = '猫咪时间线事件表';

CREATE TABLE `coordinate` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(255) NULL,
  `cat_id` BIGINT NOT NULL,
  `description` TEXT NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `uploader` VARCHAR(255) NULL,
  PRIMARY KEY (`id`)
) COMMENT = '坐标表';

-- Post and Comment Management
CREATE TABLE `post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `article` TEXT NULL,
  `author_id` INT NOT NULL,
  `like_count` INT NULL DEFAULT 0,
  `collecting_count` INT NULL DEFAULT 0,
  `comment_count` INT NULL DEFAULT 0,
  `send_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `cover_picture` VARCHAR(255) NULL,
  `is_deleted` INT NULL DEFAULT 0 COMMENT '是否删除：0否 1是',
  `is_adopted` INT NULL DEFAULT 0 COMMENT '审核状态：0待审核 1通过 2不通过',
  `approve_user_id` INT NULL,
  PRIMARY KEY (`id`)
) COMMENT = '帖子表';

CREATE TABLE `post_pics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `picture` VARCHAR(255) NULL,
  `pic_number` INT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) COMMENT = '帖子图片表';

CREATE TABLE `post_like` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `status` INT NULL COMMENT '点赞状态 1:点赞 0:取消点赞',
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) COMMENT = '帖子点赞表';

CREATE TABLE `post_favorite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `status` INT NULL COMMENT '收藏状态 1:收藏 0:取消收藏',
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) COMMENT = '帖子收藏表';

CREATE TABLE `cat_comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cat_id` BIGINT NOT NULL,
  `comment_context` TEXT NULL,
  `comment_user_id` INT NOT NULL,
  `status` INT NULL COMMENT '评论状态：10未审核 20通过 30不通过',
  `is_deleted` INT NULL DEFAULT 0,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `like_count` INT NULL DEFAULT 0,
  `is_top` INT NULL DEFAULT 0,
  `type` INT NULL COMMENT '评论类型：10小猫评论 20帖子评论',
  PRIMARY KEY (`id`)
) COMMENT = '小猫评论表';

CREATE TABLE `post_comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `type` INT NULL COMMENT '评论类型：10小猫评论 20帖子评论',
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` INT NULL COMMENT '评论状态：10待审核 20通过 30未通过',
  `is_deleted` INT NULL DEFAULT 0,
  `is_top` INT NULL DEFAULT 0,
  `comment_context` TEXT NULL,
  `like_count` INT NULL DEFAULT 0,
  `comment_user_id` INT NOT NULL,
  PRIMARY KEY (`id`)
) COMMENT = '帖子评论表';

CREATE TABLE `comment_relationship` (
  `id` BIGINT NOT NULL,
  `son_id` BIGINT NOT NULL,
  `father_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) COMMENT = '评论父子关系表';

CREATE TABLE `comment_like` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NULL COMMENT '类型：10-小猫评论 20-帖子评论',
  `target_id` INT NOT NULL COMMENT '小猫评论ID/帖子评论ID',
  `user_id` INT NOT NULL,
  `status` INT NULL COMMENT '点赞状态 1:点赞 0:取消点赞',
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) COMMENT = '评论点赞表';


-- Donation and Fund Management
CREATE TABLE `donate` (
  `id` BIGINT NOT NULL,
  `amount` BIGINT NULL,
  `cat_id` BIGINT NOT NULL,
  `cat_name` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `name` VARCHAR(255) NULL,
  `time` TIMESTAMP NULL,
  PRIMARY KEY (`id`)
) COMMENT = '捐赠表';

CREATE TABLE `fund_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_user_id` INT NULL,
  `date` DATE NULL,
  `amount` DECIMAL(10, 2) NULL,
  `type` INT NULL COMMENT '类型：1：收入 2：支出',
  `description` TEXT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) COMMENT = '资金记录表';

-- Other
CREATE TABLE `shot_link` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NULL COMMENT '记录类型：10猫猫 20帖子',
  `origin_url` VARCHAR(2083) NULL,
  `convert_url` VARCHAR(255) NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) COMMENT = '短链接表'; 